# Generated by Django 3.2 on 2022-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepix',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
