# Generated by Django 3.2 on 2022-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profilepix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepix',
            field=models.FileField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
