# Generated by Django 3.2 on 2022-05-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profilepix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepix',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
