# Generated by Django 3.2 on 2022-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_profilepix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gettutor',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='gettutor',
            name='lastname',
        ),
        migrations.AddField(
            model_name='gettutor',
            name='bustop',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gettutor',
            name='duration',
            field=models.CharField(max_length=500),
        ),
    ]
