# Generated by Django 3.2 on 2022-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220522_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettutor',
            name='Start',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
