# Generated by Django 3.2 on 2022-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_gettutor_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettutor',
            name='Start',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
