# Generated by Django 3.2 on 2022-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_gettutor_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetutor',
            name='active',
        ),
        migrations.AddField(
            model_name='activetutor',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
