# Generated by Django 3.2 on 2022-05-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220523_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='roll',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='becometutor',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='becometutor',
            name='teachinglocations',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='active',
        ),
        migrations.AddField(
            model_name='becometutor',
            name='city',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becometutor',
            name='countryofresidency',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becometutor',
            name='newsletters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='becometutor',
            name='region',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becometutor',
            name='state',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becometutor',
            name='teachingmode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalhistory',
            name='specialty',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhistory',
            name='stillactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='teachingrole',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='becometutor',
            name='sex',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportphoto', models.ImageField(upload_to='')),
                ('valiedid', models.ImageField(upload_to='')),
                ('introvideo', models.FileField(upload_to='')),
                ('tutor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.becometutor')),
            ],
        ),
    ]
