# Generated by Django 3.2 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220320_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedPostVideo',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='body',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedpost',
            name='uri',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
