# Generated by Django 3.2 on 2022-05-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220518_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='author',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
